name:                slack
version:             0.1.0.0
github:              fpclass/slack
license:             MIT
author:              Michael B. Gale <m.gale@warwick.ac.uk>
maintainer:          Michael B. Gale <m.gale@warwick.ac.uk>
copyright:           Copyright (c) Michael B. Gale

dependencies:
- aeson
- base
- data-default-class
- deriving-aeson
- http-api-data
- http-client
- http-client-tls
- mtl
- servant
- servant-client
- servant-client-core
- text

default-extensions:
- AllowAmbiguousTypes
- DataKinds
- DeriveGeneric
- DerivingVia
- FlexibleInstances
- OverloadedLists
- OverloadedStrings
- PolyKinds
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror=missing-fields
